// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-plans.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_plans_default = defineTool({
  name: "list_plans",
  title: "List subscription plans",
  description: "List Busistree subscription plans with PKR pricing, features, and limits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("plans").select("*").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { plans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-website-products.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_website_products_default = defineTool2({
  name: "list_website_products",
  title: "List website products",
  description: "List marketplace website products (pages, sections, popups) available to add to a store. Optionally filter by type.",
  inputSchema: {
    type: z.string().optional().describe("Optional filter: e.g. 'page', 'section', 'popup'")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("website_products").select("*").eq("is_enabled", true).order("sort_order");
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-integrations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_integrations_default = defineTool3({
  name: "list_integrations",
  title: "List integrations",
  description: "List marketplace integrations (WhatsApp button, analytics, forms, etc.) that can be added to a store.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("integrations").select("*").eq("is_enabled", true).order("sort_order");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { integrations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-help-articles.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_help_articles_default = defineTool4({
  name: "search_help_articles",
  title: "Search help articles",
  description: "Search Busistree help center articles by keyword in title or content.",
  inputSchema: {
    query: z2.string().min(1).describe("Search term to match against article title/content."),
    limit: z2.number().int().min(1).max(20).optional().describe("Max results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const n = limit ?? 5;
    const { data, error } = await supabase.from("help_articles").select("id, slug, title, content, category_id").or(`title.ilike.%${query}%,content.ilike.%${query}%`).limit(n);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "busistree-mcp",
  title: "Busistree",
  version: "0.1.0",
  instructions: "Read-only tools for Busistree \u2014 a Pakistan-focused portal for launching WordPress stores. Use these tools to browse subscription plans, marketplace website products (pages/sections/popups), integrations, and help center articles.",
  tools: [list_plans_default, list_website_products_default, list_integrations_default, search_help_articles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
